# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e714e7310159bfded5e05e4eff4451af12a745c9816991467f75cd567825e37bde908f5efecb600efce82c7eec5abdfe7ad13e7fe4598d87ad3642d9bd000f80

test:
  secret_key_base: 3b94ee28b7fef37f0bafe0514981304eedb3f9aeb3489525b69f0f60d281028d45f4bf79e5cc6b2427ff4cf0ba1e99e34b689d707aa06ab7d26835c62c04b4bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
